# Generated by Django 4.2.5 on 2023-09-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='event',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
