# Generated by Django 5.0.7 on 2024-09-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='smtp_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
