# Generated by Django 4.2.5 on 2023-09-19 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_service_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='main.agent'),
        ),
    ]
