# Generated by Django 4.2.5 on 2023-09-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_service_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='monitor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='svc_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
