# Generated by Django 4.2.5 on 2023-09-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_service_state_alter_service_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="state",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
