# Generated by Django 4.2.5 on 2023-12-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_ack_last_modified_alter_agent_last_checkin"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="cpu",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="mem",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="monit_version",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="os_arch",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="os_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="os_release",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="os_version",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="swap",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="uptime",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
