# Generated by Django 4.2.5 on 2024-01-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_agent_cpu_agent_mem_agent_monit_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="cycle",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
