# Generated by Django 5.0.1 on 2024-01-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_service_last_modified'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agent',
            new_name='Host',
        ),
        migrations.RemoveConstraint(
            model_name='service',
            name='unique_svc_name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='agent',
            new_name='host',
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('name', 'host'), name='unique_svc_name'),
        ),
    ]
