# Generated by Django 5.0.1 on 2024-01-27 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_agent_host_remove_service_unique_svc_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hservice', to='main.host'),
        ),
    ]
