# Generated by Django 5.0.1 on 2024-01-27 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_service_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='main.host'),
        ),
    ]
