# Generated by Django 5.0.1 on 2024-01-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_service_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ack',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Ack',
        ),
    ]
