# Generated by Django 5.0.1 on 2024-02-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_service_ack_delete_ack'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='host',
            name='unique_agent_name',
        ),
        migrations.AddConstraint(
            model_name='host',
            constraint=models.UniqueConstraint(fields=('monit_id',), name='unique_monit_id'),
        ),
    ]
