# Generated by Django 5.0.6 on 2024-05-09 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_service_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='service',
            name='last_checkin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='host',
            name='last_checkin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
