# Generated by Django 5.0.6 on 2024-05-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_service_last_modified_service_last_checkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
