# Generated by Django 5.0.6 on 2024-05-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_host_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="approved",
            field=models.BooleanField(default=True),
        ),
    ]
