# Generated by Django 5.0.6 on 2024-05-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_host_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="frozen",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="host",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
