# Generated by Django 5.0.6 on 2024-05-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_host_frozen_alter_host_approved"),
    ]

    operations = [
        migrations.RenameField(
            model_name="host",
            old_name="frozen",
            new_name="ignore",
        ),
    ]
