# Generated by Django 5.0.6 on 2024-06-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_rename_frozen_host_ignore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="HostGroup",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("host", models.ManyToManyField(db_index=True, to="main.host")),
            ],
        ),
        migrations.AddConstraint(
            model_name="hostgroup",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_hostgroup_name"
            ),
        ),
    ]
