# Generated by Django 5.0.6 on 2024-06-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_alter_host_name_hostgroup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostgroup",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
