# Generated by Django 5.0.6 on 2024-07-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_hostgroup_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostgroup",
            name="host",
            field=models.ManyToManyField(blank=True, db_index=True, to="main.host"),
        ),
    ]
