# Generated by Django 5.0.6 on 2024-07-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_alter_hostgroup_host"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostgroup",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hostgroup",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
