# Generated by Django 5.0.6 on 2024-08-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_alter_hostgroup_host"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=40)),
                ("active", models.BooleanField(default=False)),
                ("smtp_server", models.CharField(max_length=50)),
                ("smtp_port", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SlackConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=40)),
                ("active", models.BooleanField(default=False)),
                ("webhook", models.CharField(max_length=500)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
