# Generated by Django 5.0.6 on 2024-08-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_emailconnector_slackconnector"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="emailconnector",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_email_connector_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="slackconnector",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_slack_connector_name"
            ),
        ),
    ]
