# Generated by Django 5.0.6 on 2024-08-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_emailconnector_unique_email_connector_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackconnector",
            name="channel",
            field=models.CharField(default="sss", max_length=40),
            preserve_default=False,
        ),
    ]
