# Generated by Django 5.0.6 on 2024-09-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_slackconnector_channel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slackconnector",
            name="channel",
        ),
    ]
